# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'AgoraChatEThreeExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'VirgilE3Kit', '2.2.0'
  pod 'AgoraChat'
  pod 'ZSwiftBaseLib',:git =>"https://github.com/zjc19891106/ZSwiftBaseLib"
  pod 'ProgressHUD'
end
